public class Car extends Vehicle{

    private int numberOfDoors;



    public Car( int numberOfDoors, String colour, int ID ){
        super(4, ID, colour);

        this.setNumberOfDoors(numberOfDoors); //this means set the numberofdoors to the class version at the top rather than the version in the constructor

    }

    @Override   //this method creates a means of displaying the number of doors next to the specific car
    public String toString() {  // was generated by right clicking, click generate, click ok on the the ticked method. this was the last thing i did
        return "Car{" +
                "numberOfDoors=" + numberOfDoors +
                '}';
    }

    public int getNumberOfDoors() {
        return numberOfDoors;
    }

    public void setNumberOfDoors(int numberOfDoors) {
        this.numberOfDoors = numberOfDoors;
    }


    @Override
    public int Bill() {
        return 500;
    }
}
